# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import Problem11_GeneratedSolution as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "v|\te(#\x0bbh'"
    module_0.maximalPathQuality(str_0, str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    list_0 = []
    module_0.maximalPathQuality(list_0, list_0, list_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    tuple_0 = ()
    str_0 = "\n"
    module_0.maximalPathQuality(str_0, tuple_0, tuple_0)


def test_case_3():
    tuple_0 = ()
    bytes_0 = b"\x88\xa1"
    var_0 = module_0.maximalPathQuality(bytes_0, tuple_0, tuple_0)
    assert var_0 == 136


def test_case_4():
    bytes_0 = b"\x8a_\xd8"
    tuple_0 = (bytes_0, bytes_0)
    var_0 = module_0.maximalPathQuality(bytes_0, tuple_0, tuple_0)
    assert var_0 == 138


@pytest.mark.xfail(strict=True)
def test_case_5():
    bytes_0 = b"\x00;B"
    tuple_0 = (bytes_0, bytes_0)
    module_0.maximalPathQuality(bytes_0, tuple_0, tuple_0)


def test_case_6():
    bytes_0 = b"\x00R\xa1"
    tuple_0 = (bytes_0, bytes_0)
    bool_0 = True
    var_0 = module_0.maximalPathQuality(bytes_0, tuple_0, bool_0)
    assert var_0 == 0


@pytest.mark.xfail(strict=True)
def test_case_7():
    bytes_0 = b"\x03\x00%"
    tuple_0 = (bytes_0, bytes_0)
    float_0 = 265.2461532763739
    module_0.maximalPathQuality(bytes_0, tuple_0, float_0)
