# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import Problem17_GeneratedSolution as module_0


def test_case_0():
    int_0 = -266
    dict_0 = {int_0: int_0}
    var_0 = module_0.countSmaller(dict_0)
    var_1 = module_0.countSmaller(var_0)
    str_0 = "%]:>Qq\nI4N\x0bkYUe\rKe$"
    var_2 = module_0.countSmaller(str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.countSmaller(none_type_0)
