# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import Problem25_GeneratedSolution as module_0


def test_case_0():
    str_0 = "55"
    var_0 = module_0.addOperators(str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "z/*"
    module_0.addOperators(str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = -182
    module_0.addOperators(int_0, int_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "2zFtp\r#$UI;I:t\x0bKmj|"
    module_0.addOperators(str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    list_0 = []
    none_type_0 = None
    var_0 = module_0.addOperators(list_0, none_type_0)
    var_1 = module_0.addOperators(list_0, none_type_0)
    str_0 = "2zFtp\r#$UI;I:t\x0bKmj|"
    var_2 = module_0.addOperators(list_0, var_1)
    var_3 = module_0.addOperators(var_2, list_0)
    dict_0 = {}
    var_4 = module_0.addOperators(list_0, dict_0)
    var_5 = module_0.addOperators(var_2, str_0)
    bool_0 = False
    var_6 = module_0.addOperators(var_4, bool_0)
    module_0.addOperators(str_0, var_2)


@pytest.mark.xfail(strict=True)
def test_case_5():
    str_0 = "28Ft\x0b#UI;I:t\x0bKmj|"
    module_0.addOperators(str_0, str_0)


def test_case_6():
    str_0 = "505"
    none_type_0 = None
    var_0 = module_0.addOperators(str_0, none_type_0)
    var_1 = module_0.addOperators(str_0, var_0)
