# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import Problem43_GeneratedSolution as module_0
import builtins as module_1


def test_case_0():
    bool_0 = False
    var_0 = module_0.coinChange(bool_0, bool_0)
    assert var_0 == 0
    var_1 = module_1.object()


@pytest.mark.xfail(strict=True)
def test_case_1():
    object_0 = module_1.object()
    bool_0 = True
    module_0.coinChange(bool_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    float_0 = 884.058595
    module_0.coinChange(float_0, float_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "~y'o7[2zy\n+"
    bool_0 = True
    module_0.coinChange(str_0, bool_0)


def test_case_4():
    list_0 = []
    int_0 = 1956
    bytes_0 = b"\xa4\xb4\xbb\xdc\x19s\xa9(\x84\xb0S\xf5\x89\x01\xe5c\xc8n\xcd"
    var_0 = module_0.coinChange(list_0, int_0)
    assert var_0 == -1
    bool_0 = False
    var_1 = module_0.coinChange(bytes_0, bool_0)
    assert var_1 == 0


@pytest.mark.xfail(strict=True)
def test_case_5():
    int_0 = 1125
    list_0 = [int_0]
    var_0 = module_0.coinChange(list_0, int_0)
    assert var_0 == 1
    bool_0 = True
    module_0.coinChange(bool_0, bool_0)
