# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import Problem21_GeneratedSolution as module_0


def test_case_0():
    bool_0 = True
    list_0 = [bool_0]
    int_0 = module_0.countPartitions(list_0, bool_0)
    assert int_0 == 0


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.countPartitions(none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = 5408
    list_0 = [int_0]
    int_1 = module_0.countPartitions(list_0, int_0)
    assert int_1 == 0
    int_2 = 1889
    int_3 = -1227
    list_1 = [int_2, int_3, int_2]
    module_0.countPartitions(list_1, int_3)
