# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import Problem37_GeneratedSolution as module_0


def test_case_0():
    list_0 = []
    var_0 = module_0.maxEnvelopes(list_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b"\x12\xcc\x03\x83\r"
    module_0.maxEnvelopes(bytes_0)


def test_case_2():
    bytes_0 = b"\xbb\xb1"
    list_0 = [bytes_0, bytes_0]
    var_0 = module_0.maxEnvelopes(list_0)
    assert var_0 == 1
