# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import Problem47_GeneratedSolution as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "JSYARc\x0b D\nIN"
    module_0.isPathCrossing(str_0)


def test_case_1():
    str_0 = ""
    var_0 = module_0.isPathCrossing(str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    list_0 = [bool_0]
    var_0 = module_0.isPathCrossing(list_0)
    assert var_0 is False
    str_0 = "aS"
    module_0.isPathCrossing(str_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = False
    bool_1 = True
    str_0 = ".Y^E^?&V!}m{l8W7k3"
    bool_2 = True
    bool_3 = True
    dict_0 = {bool_0: bool_1, str_0: bool_2, bool_3: bool_0, bool_3: bool_0}
    module_0.isPathCrossing(dict_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    bytes_0 = b"\xb8[\xa2\xfb"
    var_0 = module_0.isPathCrossing(bytes_0)
    assert var_0 is True
    var_1 = module_0.isPathCrossing(bytes_0)
    assert var_1 is True
    module_0.isPathCrossing(var_0)
