# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import Problem48_GeneratedSolution as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    module_0.maxProduct(none_type_0)


def test_case_1():
    float_0 = 1035.127
    var_0 = module_0.maxProduct(float_0)
    assert var_0 == pytest.approx(4.2154069265870807e164, abs=0.01, rel=0.01)


def test_case_2():
    bool_0 = True
    var_0 = module_0.maxProduct(bool_0)
    assert var_0 == 1
