# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import Problem23_GeneratedSolution as module_0


def test_case_0():
    str_0 = "kiizc)e}"
    var_0 = module_0.reorderDigits(str_0)


def test_case_1():
    none_type_0 = None
    module_0.reorderDigits(none_type_0)
