# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import Problem22_GeneratedSolution as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\xceX\xa3N"
    var_0 = module_0.canPartition(bytes_0)
    module_0.canPartition(var_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = ""
    var_0 = module_0.canPartition(str_0)
    assert var_0 is True
    module_0.canPartition(var_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    float_0 = 3979.953
    module_0.canPartition(float_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bytes_0 = b"A\x03-&\x16\x9f\xfc\x04\xa7\x8cM\xaes=\xb4\x82\xc1\x83"
    var_0 = module_0.canPartition(bytes_0)
    assert var_0 is True
    bytes_1 = b"\x0e\x1c\xe6\xb8\x16\xad\x9f\xc3\x03\xdd\xb8"
    module_1.object(*bytes_1)
