# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import Problem10_GeneratedSolution as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "kkgC\x0cw0reun8QFP*)\tm#"
    module_0.cherryPickup(str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "K"
    module_0.cherryPickup(str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b"/\xb2\xfawS\xc5"
    list_0 = [bytes_0, bytes_0, bytes_0]
    var_0 = module_0.cherryPickup(list_0)
    assert var_0 == 1378
    module_0.cherryPickup(var_0)
